apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: flink
data:
  base-config: |+
{{ .Values.base_config | indent 4 }}
{{- $name := .Release.Name }}
{{ index .Values $name | toYaml | indent 2 }}
  log4j_console_properties: |+
{{ .Values.log4j_console_properties | indent 4 }}