package org.sunbird.collectioncsv.util

object CollectionTOCConstants {

  val COLLECTION_CSV_TOC_UPLOAD = "collectionTOCUpload"
  val COLLECTION_CSV_TOC_DOWNLOAD = "collectionTOCUrl"
  val COLLECTION = "collection"
  val COLLECTION_TOC_ALLOWED_MIMETYPE = "application/vnd.ekstep.content-collection"
  val COLLECTION_TOC_ALLOWED_CONTENT_TYPES = "collection_toc_allowed_content_types"
  val COLLECTION_TOC_MAX_CSV_ROWS = "collection_toc_max_csv_rows"
  val COLLECTION_CREATION_CSV_TOC_HEADERS = "collection_create_csv_toc_headers"
  val COLLECTION_CSV_IDENTIFIER_HEADER = "csv_folder_identifier_col_header"
  val COLLECTION_UPDATE_CSV_TOC_HEADERS = "collection_update_csv_toc_headers"
  val COLLECTION_TOC_CREATE_CSV_MANDATORY_FIELDS = "collection_toc_create_csv_mandatory_fields"
  val COLLECTION_TOC_UPDATE_CSV_MANDATORY_FIELDS = "collection_toc_update_csv_mandatory_fields"
  val FOLDER_HIERARCHY_COLUMNS = "collection_csv_hierarchy_headers"
  val COLLECTION_CSV_QR_COLUMNS = "collection_csv_qr_headers"
  val COLLECTION_CSV_LINKED_CONTENT_FIELDS = "collection_csv_linked_content_fields"
  val COLLECTION_CSV_LINKED_CONTENT_SEQ = "collection_csv_linked_content_seq"
  val COMMA_SEPARATOR = ", "
  val X_CHANNEL_ID = "X-Channel-Id"
  val DIALCODE = "dialcode"
  val MAPPED_TOPICS_HEADER = "collection_csv_mapped_topics_header"
  val CSV_COLLECTION_NAME_HEADER = "collection_csv_collection_name"
  val COLLECTION_CSV_FILE_EXTENSION = ".csv"
  val COLLECTION_TYPE_TO_UNIT_TYPE = "collection_content_type_unit_type"
  val CHILD_NODES = "childNodes"
  val DEPTH = "depth"
  val LEVEL = "level"
  val COLLECTION_OUTPUT_TOC_HEADERS = "collection_output_toc_headers"
  val CHILDREN = "children"
  val UPDATE = "UPDATE"
  val CREATE = "CREATE"
  val DIAL_CODES = "dialcodes"
  val DIAL_CODE_REQUIRED = "dialcodeRequired"
  val NO = "No"
  val YES = "Yes"
  val QR_CODE_REQUIRED = "QR Code Required?"
  val QR_CODE = "QR Code"
  val KEYWORDS = "keywords"
  val MAX_ALLOWED_CONTENT_SIZE = "max_allowed_content_size"
  val TOPIC = "topic"
  val CONTENT_TYPE = "contentType"
  val IDENTIFIER = "identifier"
  val DESCRIPTION = "description"
  val LIMIT = "limit"
  val NAME = "name"
  val LINKED_CONTENT = "linkedContent"
  val CHANNEL = "channel"
  val CONTENT = "content"
  val FRAMEWORK = "framework"
  val VERSION_KEY = "versionKey"
  val SUNBIRD_TOC_MAX_FIRST_LEVEL_UNITS = "sunbird_toc_max_first_level_units"
  val INDEX = "index"
  val SUNBIRD_CONTENT_GET_HIERARCHY_API = "sunbird_get_hierarchy_api"
  val RESULT = "result"
  val CONTENT_TYPE_HEADER = "Content-Type"
  val BEARER = "Bearer "
  val MESSAGES = "messages"
  val APPLICATION_JSON = "application/json"
  val REQUEST = "request"
  val SEARCH = "search"
  val FILTERS = "filters"
  val FIELDS = "fields"
  val MIME_TYPE = "mimeType"
  val X_AUTHENTICATED_USER_TOKEN = "x-authenticated-user-token"
  val CATEGORIES = "categories"
  val CODE = "code"
  val TERMS = "terms"
  val TOC_URL = "tocUrl"
  val TTL = "ttl"

  val EKSTEP_BASE_URL = "ekstep_api_base_url"
  val LEARNING_SERVICE_BASE_URL = "learning_service.api.base_url"
  val SUNBIRD_AUTHORIZATION = "learning_service.api.auth_key"
  val SUNBIRD_CS_BASE_URL = "sunbird_cs_base_url"

  val FRAMEWORK_READ_API_URL = "framework_read_api_url"
  val SUNBIRD_DIALCODE_SEARCH_API = "sunbird_dialcode_search_api"
  val SUNBIRD_CONTENT_SEARCH_URL = "sunbird_content_search_url"
  val UPDATE_HIERARCHY_API = "sunbird_update_hierarchy_api"
  val LINK_DIAL_CODE_API = "sunbird_link_dial_code_api"

}
