### Default variable file for learning-service ###

api_namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: shouryasolanki/learning-service
image_tag: latest
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 8080
  targetport: 8080
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%
serviceType: ClusterIP
 
cassandra_connection: cassandra-db.knowlg-db.svc.cluster.local:9042
redis_connection: redis-db.knowlg-db.svc.cluster.local
neo4j_domain_connection: neo4j-db.knowlg-db.svc.cluster.local:7687
neo4j_all_connection: neo4j-db.knowlg-db.svc.cluster.local:8687  
kafka_connection: kafka.knowlg-db.svc.cluster.local:9092
es_connection: elasticsearch.knowlg-db.svc.cluster.local:9200
cloudstorage_relative_path_prefix_content: CONTENT_STORAGE_BASE_PATH
cloudstorage_metadata_list: ["appIcon", "artifactUrl", "posterImage", "previewUrl", "thumbnail", "assetsMap", "certTemplate", "itemSetPreviewUrl", "grayScaleAppIcon", "sourceURL", "variants", "downloadUrl", "streamingUrl", "toc_url", "data", "question", "solutions", "editorState", "media", "pdfUrl", "transcripts"]
cloudstorage_read_base_path: "https://sunbirddevbbpublic.blob.core.windows.net"
cloudstorage_write_base_path: ["https://sunbirdstagingpublic.blob.core.windows.net", "https://sunbirddevbbpublic.blob.core.windows.net"]
cloud_storage_env: "sunbird"
cloud_storage_content_folder: "content"
cloud_storage_asset_folder: "assets"
cloud_storage_artefact_folder: "artifact"
cloud_storage_bundle_folder: "bundle"
cloud_storage_media_folder: "media"
cloud_storage_ecar_folder: "ecar_files"
cloud_storage_itemset_folder: "itemset"
content_keyspace_name: content_store
hierarchy_keyspace_name: hierarchy_store
content_hierarchy_table: content_hierarchy
framework_hierarchy_table: framework_hierarchy
dialcode_keyspace_name: dialcode_store
dialcode_keyspace_table: dial_code
system_config_table: system_config
publisher_keyspace_table: publisher
assessment_keyspace_name: sunbird_content_store
assessment_keyspace_table: question_data