# apiVersion: v2
# name: superset
# description: A Helm chart for Apache Superset

# # A chart can be either an 'application' or a 'library' chart.
# #
# # Application charts are a collection of templates that can be packaged into versioned archives
# # to be deployed.
# #
# # Library charts provide useful utilities or functions for the chart developer. They're included as
# # a dependency of application charts to inject those utilities and functions into the rendering
# # pipeline. Library charts do not define any templates and therefore cannot be deployed.
# type: application

# # This is the chart version. This version number should be incremented each time you make changes
# # to the chart and its templates, including the app version.
# version: 1.0.0

# # This is the version number of the application being deployed. This version number should be
# # incremented each time you make changes to the application.
# appVersion: 1.20


apiVersion: v2
appVersion: "1.0"
description: Apache Superset is a modern, enterprise-ready business intelligence web application
name: superset
maintainers:
  - name: craig-rueda
    email: craig@craigrueda.com
    url: https://github.com/craig-rueda
version: 0.3.5
dependencies:
- name: redis
  version: 12.3.3
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
