package org.sunbird.content.util

object FlagConstants {
  val CONTENT_OBJECT_TYPE: String = "Content"
  val FLAGGED: String = "Flagged"
  val FLAG_DRAFT: String = "FlagDraft"
  val RETIRED: String = "Retired"
  val MIME_TYPE: String = "mimeType"
  val MIME_TYPE_COLLECTION: String = "application/vnd.ekstep.content-collection"
  val STATUS: String = "status"
  val IDENTIFIER: String = "identifier"
  val VERSION_KEY: String = "versionKey"
  val CONTENT: String = "content"
  val NODE_ID: String = "node_id"
  val IMAGE_SUFFIX: String = ".img"
  val MODE: String = "mode"
  val EDIT: String = "edit"
  val READ: String = "read"
  val VERSIONING: String = "versioning"
  val DISABLE: String = "disable"
  val ROOT_ID: String = "rootId"
  val HIERARCHY: String = "hierarchy"
  val LAST_STATUS_CHANGED_ON: String = "lastStatusChangedOn"
  val HIERARCHY_PREFIX: String = "hierarchy_"
  val COLLECTION_SCHEMA_NAME: String = "collection"
  val SCHEMA_NAME: String = "schemaName"
  val ERR_CONTENT_BLANK_OBJECT_ID: String = "ERR_CONTENT_BLANK_OBJECT_ID"
  val ERR_INVALID_CONTENT: String = "ERR_INVALID_CONTENT"
  val ERR_CREATING_IMAGE_NODE: String = "ERR_CREATING_IMAGE_NODE"
  val ERR_UPDATING_IMAGE_NODE: String = "ERR_UPDATING_IMAGE_NODE"
  val ERR_UPDATING_ORIGINAL_NODE: String = "ERR_UPDATING_ORIGINAL_NODE"
  val ERR_GETTING_HIERARCHY: String = "ERR_GETTING_HIERARCHY"
}
