db_namespace: knowlg-db
replicaCount: 1
image: pallakartheekreddy/neo4j:3.3.0
authEnabled: false
network:
  port: 7474
neo4j:
  name: neo4j
  resources:
    cpu: "0.5"
    memory: "2Gi"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi
kafka_connection: kafka-headless.knowlg-db.svc.cluster.local:9092
learning_graph_events: dev.learning.graph.events