apiVersion: v1
kind: Pod
metadata:
    name: testclient
    namespace: kafka
spec:
  containers:
  - name: kafka
    image: solsson/kafka:latest
    command:
    - sh
    - -c
    - "exec tail -f /dev/null"
