package org.sunbird.utils

object HierarchyErrorCodes {
    val ERR_INVALID_ROOT_ID: String = "ERR_INVALID_ROOT_ID"
    val ERR_CONTENT_NOT_FOUND: String = "ERR_CONTENT_NOT_FOUND"
    val ERR_HIERARCHY_NOT_FOUND: String = "ERR_HIERARCHY_NOT_FOUND"
    val ERR_HIERARCHY_UPDATE_DENIED: String = "ERR_HIERARCHY_UPDATE_DENIED"
    val ERR_ADD_HIERARCHY_DENIED: String = "ERR_ADD_HIERARCHY_DENIED"
    val ERR_REMOVE_HIERARCHY_DENIED: String = "ERR_REMOVE_HIERARCHY_DENIED"

}
