package org.sunbird.graph.dac.enums;

public enum GraphDACErrorCodes {
    
    ERR_GRAPH_NULL_DB_NODE,
    
    ERR_GRAPH_NULL_DB_REL,

    ERR_CREATE_RELATION_MISSING_REQ_PARAMS,
    
    ERR_GET_NODE_MISSING_REQ_PARAMS,

    ERR_GET_NODE_LIST_MISSING_REQ_PARAMS,

    ERR_CHECK_LOOP_MISSING_REQ_PARAMS;
}
