package org.sunbird.utils

object AssessmentConstants {
  val REQUIRED_KEYS: List[String] = List("createdBy", "createdFor")
  val ERR_INVALID_REQUEST: String = "ERR_INVALID_REQUEST"
  val ERR_INVALID_OBJECT_TYPE: String = "ERR_INVALID_OBJECT_TYPE"
  val COPY_SCHEME: String = "copyScheme"
  val MIME_TYPE: String = "mimeType"
  val QUESTIONSET_MIME_TYPE: String = "application/vnd.sunbird.questionset"
  val STATUS: String = "status"
  val COPY_TYPE: String = "copyType"
  val SCHEMA_NAME: String = "schemaName"
  val VERSION: String = "version"
  val ROOT_ID: String = "rootId"
  val MODE: String = "mode"
  val COPY_TYPE_SHALLOW: String = "shallow"
  val QUESTIONSET_SCHEMA_NAME: String = "questionset"
  val SCHEMA_VERSION: String = "1.0"
  val IDENTIFIER: String = "identifier"
  val QUESTION: String = "question"
  val HIERARCHY: String = "hierarchy"
  val CHILDREN: String = "children"
  val ORIGIN: String = "origin"
  val ORIGIN_DATA: String = "originData"
  val CONTENT_TYPE: String = "contentType"
  val ROOT: String = "root"
  val NODES_MODIFIED: String = "nodesModified"
  val VISIBILITY: String = "visibility"
  val METADATA: String = "metadata"
  val VERSION_KEY: String = "versionKey"
  val PRIMARY_CATEGORY : String = "primaryCategory"
  val QUESTIONSET : String = "questionSet"
  val OBJECT_TYPE : String = "objectType"
  val COPY_TYPE_DEEP: String = "deep"
  val QUESTION_MIME_TYPE: String = "application/vnd.sunbird.question"
  val QUESTION_SCHEMA_NAME: String = "question"
  val VISIBILITY_PARENT: String = "Parent"
  val VISIBILITY_DEFAULT: String = "Default"
}
